#pragma once
void runOneDimensionalVectorIntProblems();
void runOneDimensionalVectorCharProblems();
int isDigit(char c);
int isVowel(char c);
int isConsonant(char c);
int isUppercase(char c);
void showSumOfPositives();
void addPositivesToVectorAndShowThem();
void showMaxWithVector();
void testVectorBasics();
int readNumbersIntoVector(int* out, int maxSize);
void displayElements(const int* pIn, int elementsCount);
void readValuesWhilePositive(const int* pIn, int elementsCount);
void displaySum(const int* pIn, int elementsCount);
void displayMax(const int* pIn, int elementsCount);
void displayMin(const int* pIn, int elementsCount);
void displayEvenElements(const int* pIn, int elementsCount);
void displayElementsOnEvenIndices(const int* pIn, int elementsCount);
void displayElementsOnEvenIndices(const int* pIn, int elementsCount);
void displayElementsOnIndicesMultiplesOfX(const int* pIn, int elementsCount, int x);
void displayMultiplesOfX(const int* pIn, int elementsCount, int x);
void displayCharactersInReverse(const char* pIn, int elementsCount);
void displayNumericChars(const char* pIn, int elementsCount);
void displayVowels(const char* pIn, int elementsCount);
void displayConsonants(const char* pIn, int elementsCount);
void displayUppercaseLetters(const char* pIn, int elementsCount);
void runMatrixProblems();
void readNumbersIntoMatrix(int** ppMatrix, int* nrRows, int* rowLength);
void displayMatrixElements(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixSum(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixEvenElements(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixOddElements(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixPrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixSecondaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixElementsAbovePrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixElementsBeneathPrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMinOnMatrixPrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMaxOnMatrixSecondaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixSumAbovePrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMatrixSumBeneathPrimaryDiagonal(const int* pMatrix, int nrRows, int rowLength);
void displayMinRowElement(const int* pMatrix, int nrRows, int rowLength);
void displayMaxColumnElement(const int* pMatrix, int nrRows, int nrColumns);